data_path: /content/data/imagenet100
model_size: ViT-B/16
alpha: 0.5
n_samples: null
batch_size: 32
n_run: 10
patch_n: 50
methods:
  - clip:
      name: clip
      enabled: true
  - clip-e:
      name: clip-e
      enabled: true
  - cupl:
      name: cupl
      enabled: true
  - ours:
      name: ours
      enabled: true
      image_scale: 4.0
      text_scale: 2.0
