alpha: 0.5
batch_size: 16
data_path: /content/data/oxford_pets/oxford-iiit-pet
dataset: oxford_pet
methods:
- clip:
    enabled: true
    name: clip
- clip-e:
    enabled: true
    name: clip-e
- clip-d:
    enabled: true
    name: clip-d
- waffle:
    enabled: true
    name: waffle
- cupl:
    enabled: true
    name: cupl
- ours:
    enabled: true
    image_scale: 4.0
    name: ours
    text_scale: 2.0
model_size: ViT-B/16
n_run: 10
n_samples: 60
patch_n: 60
